### ISSUE TITLE
mac 下运行出错

### ISSUE THREAD

**Issue by chen366690712** [linG5821/Studio3TCrack#10]
app $ java -jar -XstartOnFirstThread ./studio-3t-start-2019-2.1.jar
java.io.FileNotFoundException: /Applications/Studio%203T.app/Contents/Resources/app/data-man-mongodb-ent-2019.2.1.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at com.ling.Start.getClassNameByJar(Start.java:80)
        at com.ling.Start.doStart(Start.java:32)
        at com.ling.Start.main(Start.java:16)

**Comment by 2First** [comment]
你好，现在好了吗？
他那个bash的脚本直接仿照这个改下路径就好了吗？还是
# ! /bin/bash
nohup java -jar -XstartOnFirstThread /Users/xxx/Applications/Studio3T/app/studio-3t-start-mac.jar >/dev/null 2>&1 &
看到他以&结尾，是不是没写完啊，不会这个脚本，可以的话可以贡献一份吗，
谢谢！！！

**Comment by chen366690712** [comment]
i

> 你好，现在好了吗？
> 他那个庆典的脚本直接仿照这个改下路径就好了吗？还是
> 
> # ！/斌/庆典
> nohup java -jar -XstartOnFirstThread /Users/xxx/Applications/Studio3T/app/studio-3t-start-mac.jar> / dev / null 2>＆1 
> ＆看到他以＆结尾，是不是没写完啊，不会这个脚本，可以的话可以贡献一份吗，
> 谢谢！

没解决，我的路径中有空格，是用官方安装包的。

**Comment by 2First** [comment]
额，网上太难找到MAC的破解版了，还没能破解过来找份的，哈哈哈

**Comment by linG5821** [comment]
@chen366690712 No spaces in the path Studio%203T

**Comment by chen366690712** [comment]
> @chen366690712 No spaces in the path Studio%203T

我的是mac ，是有空格的。

**Comment by linG5821** [comment]
@2First  The last & stands for background operation

**Comment by linG5821** [comment]
@chen366690712 I suggest that you copy the dependency packages into a separate directory

**Comment by chen366690712** [comment]
> @ chen366690712我建议你将依赖包复制到一个单独的目录中
/Applications/Studio 3T.app/Contents/Resources/app
这是我的文件路径

**Comment by linG5821** [comment]
Of course you can try to use the full MAC version of the package under the release page, note that it needs to be added  **-XstartOnFirstThread**  at runtime.

**Comment by linG5821** [comment]
@chen366690712 Copy the jar package under the app and do not execute it directly in the installation directory

**Comment by chen366690712** [comment]
> @ chen366690712复制应用程序下的jar包，不要直接在安装目录中执行它

谢谢，我复制到/Downloads/app 执行命令可以了

**Comment by 2First** [comment]
您好，


看到我下载的好像不是Studio 3T的2019.2.1版本，找了下没找到，能否发我一个MAC的这个版本可以吗？


谢谢！！！





在 2019-04-26 18:24:17，"成长中的诺诺" <notifications@github.com> 写道：


@ chen366690712复制应用程序下的jar包，不要直接在安装目录中执行它

谢谢，我复制到/Downloads/app 执行命令可以了

**Comment by linG5821** [comment]
Relase have a full build jar  use commond ` java -jar -XstartOnFirstThread mac-start.jar`  run it

**Comment by 2First** [comment]
你好，我没用batch,Mac上直接运行命令，下载的这个jar包：studio-3t-start-2019-2.1.jar改名studio-3t-start-mac.jar放在app里面，app里面的jar 都没动，在此目录下运行命令：java -jar -XstartOnFirstThread ./studio-3t-start-mac.jar报错，无法识别，问下这个是我哪里操作失误了吗？












At 2019-05-24 11:33:37, "linG" <notifications@github.com> wrote:


Relase have a full build jar use commond java -jar -XstartOnFirstThread mac-start.jar run it

**Comment by 2First** [comment]
你好！
      
     我好像弄好了，咨询一个问题，是不是我每次运行都要去通过bash去启动，因为我发现我用之前的app图标启动，他是有快到期2天的提示的，但是用到您的batsh启动的话 是没有时间限制的，所以，我这是已经弄好了吗，还是？？？


  






At 2019-05-24 11:33:37, "linG" <notifications@github.com> wrote:


Relase have a full build jar use commond java -jar -XstartOnFirstThread mac-start.jar run it

**Comment by cocoongg** [comment]
> 你好！ 我好像弄好了，咨询一个问题，是不是我每次运行都要去通过bash去启动，因为我发现我用之前的app图标启动，他是有快到期2天的提示的，但是用到您的batsh启动的话 是没有时间限制的，所以，我这是已经弄好了吗，还是？？？ At 2019-05-24 11:33:37, "linG" <notifications@github.com> wrote: Relase have a full build jar use commond java -jar -XstartOnFirstThread mac-start.jar run it — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.


你好，我下载的2019.3版本的studio 2t，用这个破解里面的studio-3t-start-2019-2.1.jar文件，貌似不行啊，能分享下你的操作步骤吗？
