### ISSUE TITLE
window下使用 没有看出有什么效果  用的是最新版2019.3

### ISSUE THREAD

**Issue by lhzsdnu** [linG5821/Studio3TCrack#12]

**Comment by linG5821** [comment]
current jar crack success in Studio3T2019.2.1

**Comment by linG5821** [comment]
Studio3T latest version no test

**Comment by porfavor** [comment]
Meet the same problem. I tried to find the 2019.2.1 installer, but didn't get it.
If you have the version, please send a copy to me.
Thanks, my email is: 10880565@qq.com

**Comment by linG5821** [comment]
https://github.com/linG5821/Studio3TCrack/releases
 Here have you need. It has been build.
