### ISSUE TITLE
你好，我用了最新的2019.3版本的Studio 3T，在MAC环境下没生效，请问是什么问题

### ISSUE THREAD

**Issue by cocoongg** [linG5821/Studio3TCrack#13]

**Comment by cocoongg** [comment]
我的操作是：
   1. 官网下载：2019.3.0版本，点击安装好
   2.进入安装目录的Resources/app下，把此目录下的所有jar包移除到Resources/xx目录里，xx目录是我新建的目录
   3. 把下载好的studio-3t-start-2019-2.1.jar文件拷贝到Resources/app目录
   4. 命令行进入Resources/app目录，运行java -jar -XstartOnFirstThread ./studio-3t-start-2019-2.1.jar或者使用绝对路径java -jar -XstartOnFirstThread /Applications/Studio\ 3T.app/Contents/Resources/app/studio-3t-start-2019-2.1.jar 
   5. 上一步的命令，直接就返回了，命令行没有任何输出，应用程序也没有启动

**Comment by linG5821** [comment]
Studio3T latest version not test .Please use the built version  https://github.com/linG5821/Studio3TCrack/releases
