### ISSUE TITLE
How to run on windows with the new method?

### ISSUE THREAD

**Issue by Spider08** [linG5821/Studio3TCrack#15]
Create a bat file and run like this with your new method ?
java -jar C:\LK\Temp\studio-3t-x64\data-man-mongodb-ent-2019.2.1.jar t3.dataman.mongodb.app.ad

It is giving errors like JNI error.
Exception in thread "main" java.lang.NoClassDefFoundError

**Comment by linG5821** [comment]
Sorry an error occurred while updating the document.
It has been updated again.

**Comment by Spider08** [comment]
java -cp C:\LK\Temp\studio-3t-x64\data-man-mongodb-ent-2019.2.1.jar t3.dataman.mongodb.app.ad

Same error as before

**Comment by linG5821** [comment]
I'm not sure, from the exception can only know is the problem of dependency, please ask whether there are other Studio3T dependencies in the current directory
