### ISSUE TITLE
Failed to write to global exception log

### ISSUE THREAD

**Issue by rortizpe** [linG5821/Studio3TCrack#20]
Error with spaces
![image](https://user-images.githubusercontent.com/25441633/61575450-8df2f300-aa91-11e9-8db6-c7c9b08dbd7c.png)
Error without space
![image](https://user-images.githubusercontent.com/25441633/61575469-c1ce1880-aa91-11e9-9a38-f6b71b0c4079.png)
 please help

**Comment by newbigland** [comment]
MacOS 也遇到这个问题
![Xnip2019-07-20_18-46-59](https://user-images.githubusercontent.com/31641109/61577795-e91ef700-ab1e-11e9-978c-6c47b8c2f567.jpg)

**Comment by linG5821** [comment]
About Failed to write to global exception log 
Please check whether the.3T file under the Users/ XXX/ directory has writing permission or whether this directory exists
You can first execute the version downloaded from the official website to make it generate a file before executing

**Comment by krainz** [comment]
I have the same error.
![image](https://user-images.githubusercontent.com/2731312/61760155-3c35ca00-adfd-11e9-83e5-65e30fba5203.png)

**Comment by zhuanshicong** [comment]
The directiory exists with correct permission  but same error occurred.

**Comment by zhuanshicong** [comment]
I found the point.  The new version java will stop that command running.

**Comment by linG5821** [comment]
new method have updated

**Comment by KevinDenys** [comment]
How do I fix this, I have the same issue
