### ISSUE TITLE
mac下运行命令后报错

### ISSUE THREAD

**Issue by Vincyblue** [linG5821/Studio3TCrack#21]
![1563806529905](https://user-images.githubusercontent.com/29794912/61641845-72c2f600-acd2-11e9-8730-b7ba5260e38f.jpg)
路径啥的应该没问题 到类的时候报错了

**Comment by linG5821** [comment]
Method names may change with new versions of confusion

**Comment by linG5821** [comment]
![image](https://user-images.githubusercontent.com/33996782/61686740-223fad00-ad53-11e9-82f0-7f1b0dcfee37.png)
IThe latest download is version 2019.3.0, which is currently available

**Comment by Vincyblue** [comment]
OK, I'll try the lastest version again👌
