### ISSUE TITLE
Linux 下要怎么使用

### ISSUE THREAD

**Issue by vowers** [linG5821/Studio3TCrack#4]
希望添加Linux下的启动方式啊

**Comment by wung** [comment]
ubuntu 下如何使用？

**Comment by linG5821** [comment]
请尝试mac版的jar 如果不可用 可以尝试反编译一下jar包在Linux重新构建 即可使用

**Comment by linG5821** [comment]
已经上传通用的jar包只需要在Linux环境下安装jre即可使用，请查看Release
